### ISSUE TITLE
Writer Access Request

### ISSUE THREAD

**Issue by edwinnglabs** [conda-forge/orbit-ml-feedstock#6]
### Comment:

Is it possible to get the writer access as a core contributor of the underlined package `orbit-ml`? @sugatoray  Same question in the PR #5

**Comment by sugatoray** [comment]
Yes. I would like to add you as a co-maintainer. 

Please see my comment [here](https://github.com/conda-forge/orbit-ml-feedstock/pull/5#issuecomment-1374370894)
